services:
  - type: private
    name: mysql-server
    env: docker
    plan: free
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_DATABASE
        value: myappdb
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
